apiVersion: apps/v1
kind: Deployment
metadata:
  name: mace-deployment
  namespace: mace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mace
  template:
    metadata:
      labels:
        app: mace
    spec:
      containers:
        - name: mace
          image: cs125/mace:2020.4.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: TZ
              value: "America/Chicago"
            - name: ENVIRONMENT
              value: "production"
            - name: MONGODB
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGODB
            - name: GOOGLE
              value: 948918026196-p399ooibc7pr0ci7ida63jb5a6n4vsik.apps.googleusercontent.com
---
apiVersion: v1
kind: Service
metadata:
  name: mace-service
  namespace: mace
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8888
  selector:
    app: mace
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: mace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-redirect-from: /
    nginx.ingress.kubernetes.io/proxy-redirect-to: /mace/
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: mace-ingress
spec:
  rules:
    - host: cs125-cloud.cs.illinois.edu
      http:
        paths:
          - path: /mace(/|$)(.*)
            backend:
              serviceName: mace-service
              servicePort: 80
